[global]
location = europe-west3
use_vertexai = True
project_id = project-495bdca4-ac50-4df5-bb6
#ssl_cert_file = C:\Users\umreshi\Downloads\db-endpoint-cacerts-export.pem
#curl_ca_bundle = C:\Users\umreshi\Downloads\db-endpoint-cacerts-export.pem
#grpc_default_ssl_roots_file_path = C:\Users\umreshi\Downloads\db-endpoint-cacerts-export.pem
grpc_ssl_cipher_suites = HIGH+ECDSA
grpc_dns_resolver = native
google_api_use_rest = None
local_file_path = D:\Hackathon-final\files\Credit_Card_Fraud_Detection.pdf
bucket_name = vertex-reporting-ai-gcs
skip_ingestion = Y
model_name = gemini-2.5-flash
retry_attempts = 3
temperature = 0.2
dataset_name = reporting_ai_dataset
table_name = DOCUMENT_CHUNKS
embedding_model = text-embedding-004
api_transport = rest
price_per_tb = 5.0
download_dir = gs://vertex-reporting-ai-gcs/downloads
chunk_size=1000
chunk_overlap=200
batch_size=20
gcs_uri=gs://vertex-reporting-ai-gcs/Credit_Card_Fraud_Detection.pdf
